[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
prompt_marketplace = "CBrB6yQSi9pcxKuRR1uPjj6NLipfpZKYYT71c3gaFf1Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
